### ISSUE TITLE
[功能建议]导入zh_cn.json

### ISSUE THREAD

**Issue by ZHAY10086** [Maz-T/Minecraft-Mods-Translator#1]
能不能增加导入现有zh_cn.json文件的功能，不然对于模组更新很难跟进。

**Comment by Tryanks** [comment]
当zh_cn.json文件与您打开的en_us.json处于同一文件夹下，事实上是会读取zh_cn.json文件并同步进度的。

**Comment by ZHAY10086** [comment]
抱歉，之前文件名称没改导致没有自动读取，还以为没有这个功能呢。
