### ISSUE TITLE
[Bug报告] 小bug：多余的回车

### ISSUE THREAD

**Issue by HaloSense** [Maz-T/Minecraft-Mods-Translator#4]
在当前词条编辑完毕后，如果光标不位于词条文本末尾，按下回车键切换到下一条时，上一词条文本会在光标位置处错误地添加一个回车符（’\n‘）。

**Comment by Tryanks** [comment]
按下换行键时的逻辑为：翻译后词条与原词条的换行符数量相同时，切换到下一词条；否则将不会切换词条，而是在光标处添加一个换行符。
能否帮忙核实一下当时是否是翻译文本换行符与原文不一致的情况导致的这一现象？

**Comment by HaloSense** [comment]
说实话这个不是很好测，我没想明白怎么测。

我现在但凡光标不在翻译文本结尾时点下回车就必定插入空格，**并且切换到下一个词条**。

也许是我没遇到原文有空格的情况，我测试一下。

**Comment by HaloSense** [comment]
刚才写了一个简单的json测试了一下。

```
{
    "testkey.no_enter": "No Enter",
    "testkey.one_enter": "One\nEnter",
    "testkey.two_enters": "Two\n(2)\nEnters"
}
```

放到工具里翻译的时候除了最后一条（因为是最后一条所以不会跳转），另外两个key在光标放在中间的时候按下回车，都会在当前位置加一个回车**然后切换到下一条**。

**Comment by HaloSense** [comment]
以及发现另外一个现象：上面列出的三个key在翻译工具内没有正常显示下划线，而是显示为`testkey.oneenter`, etc.

请核实。
