### ISSUE TITLE
[Bug报告]对于语法高亮功能

### ISSUE THREAD

**Issue by ArgonCrystal** [Maz-T/Minecraft-Mods-Translator#7]
在翻译的时候发现对于
$(br)$(li)On a $(item)Force Sword$()
$(item)Baconator$() 
$(l:forcecraft:infuser/bacon)Bacon$()
这种语法无法识别

**Comment by ArgonCrystal** [comment]
还有对于翻译进度的检测问题，在自动检测并导入zh_cn后直接显示495/495，但实际是还有20多行是没有翻译的。

**Comment by Tryanks** [comment]
请对原文配图，本内容被Github文本序列化无法正常读取。
另外 ，请确定您所提出的“语法”是在诸多MOD语言文本中被广泛使用的格式，而不是仅在这一个MOD/这一个作者的MOD中出现的，由MOD作者自定义的格式。
并非不愿意增加新特性，只是如果专为此类特例添加解决方案，则会导致在面对其它绝大部分项目时产生额外计算，浪费算力与用户体验。

关于翻译进度问题，烦请贴上“未翻译”的词条的截图。此类BUG较为重大，我会在锁定问题后尽快修复。

**Comment by ArgonCrystal** [comment]
![image](https://user-images.githubusercontent.com/76279239/187629731-6f885ee9-74e0-475f-b7f7-4c153504b1f8.png)

**Comment by ArgonCrystal** [comment]
看一看见好几个未翻译的key被识别√了，还有刚才我翻译过程中出现了崩溃，导致4个key的翻译文本未保存。
奔溃过程描述：
1、在翻译的那一栏输完翻译文本；
2、发现左侧的key列表未同步进行变更；
3、用鼠标点击了左侧翻译完成的同一个key的列表；
4、程序出现未响应，3秒后程序崩溃自动关闭。
5、使用程序版本[Translator 0.1.3](https://github.com/Tryanks/Minecraft-Mods-Translator/releases/tag/v0.1.3)

**Comment by Tryanks** [comment]
关于此类情况可能是一个无解的情况。程序判断中文是否存在翻译，判断的是中文是否有文字内容。因为存在一些语言文本只有符号文字，或者有一些不应翻译的内容（例如%s km，则中文通常会沿用%s km，而不是翻译成%s千米），导致翻译后文本和原文相同的情况，这种情况不能将其标记为“未翻译”。
后续我会想其它解决方案来尝试解决此问题，例如在已有的[翻译模式]、[审阅模式]之外添加第三种模式等。
