### ISSUE TITLE
[Bug报告] 使用过程中崩溃

### ISSUE THREAD

**Issue by ArgonCrystal** [Maz-T/Minecraft-Mods-Translator#8]
奔溃过程描述：
1、在翻译的那一栏输完翻译文本;
2、发现左侧的key列表未同步进行变更;
3、用鼠标点击了左侧翻译完成的同一个key的列表;
4、程序出现未响应，3秒后程序崩溃自动关闭。
5、使用程序版本[Translator 0.1.3](https://github.com/Tryanks/Minecraft-Mods-Translator/releases/tag/v0.1.3)
崩溃前截图
![image](https://user-images.githubusercontent.com/76279239/187637352-5a47042c-6519-4461-ba9d-c3b50801e739.png)

**Comment by ArgonCrystal** [comment]
我在事后复现的几次中发现了区别，在最大化程序和程序窗口默认大小的下，分别进行了同样的步骤，默认窗口下正常，在最大化程序窗口下重复同样步骤，程序崩溃。

**Comment by ArgonCrystal** [comment]
后续我多次重复同样操作，得出以下结论
1、和程序窗口大小没有关系，是概率性崩溃。
2、正常操作流程是翻译完文本点点提交同步文本更改，但未点提交就更换key值项目，就会导致程序崩溃。

**Comment by ArgonCrystal** [comment]
程序崩溃后遗症：
![image](https://user-images.githubusercontent.com/76279239/188065993-109decbd-67d9-410f-9273-83f3cfe293e5.png)
如图，猜测可能因为自动补完功能与程序崩溃导致重复补完。

**Comment by ArgonCrystal** [comment]
![image](https://user-images.githubusercontent.com/76279239/188066180-eecec78f-96db-4009-b8fe-5b6078f33c1a.png)
这是我这份翻译的奔溃奇景

**Comment by ArgonCrystal** [comment]
建议好好改进这个功能，或者提供关闭选项。

**Comment by Tryanks** [comment]
感谢反馈。明天会更新下个版本并修复包括本issue在内的已知问题，并优化词条的跳转逻辑。
之后不再维护WPF版本的工具，将全面重构转向Avalonia。
